/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import AirdropContractAbi from "../../hardhat/constants/abis/AirdropContract.json";
import BondingCurveAbi from "../../hardhat/constants/abis/BondingCurve.json";
import CultAbi from "../../hardhat/constants/abis/Cult.json";
import CultFactoryAbi from "../../hardhat/constants/abis/CultFactory.json";
import CultRewardsAbi from "../../hardhat/constants/abis/CultRewards.json";
import { Abi } from "viem";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    CultRewards: {
      address: "0x8A7368B073602B4a7C944F903cA6963C51A09f16",
      abi: CultRewardsAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    BondingCurve: {
      address: "0xb45f6688F2ed5458C11393699C325E7c5e50f9D5",
      abi: BondingCurveAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    AirdropContract: {
      address: "0xC0Ac5874e0a09B40c96e13833bdA34B7ad46D7c1",
      abi: AirdropContractAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    Cult: {
      address: "0xc0D52DB90019dc3F73b301C60A6586cfe35D87F8",
      abi: CultAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [
        "0x60187Bc4949eE2F01b507a9F77ad615093f44260",
        "0x8A7368B073602B4a7C944F903cA6963C51A09f16",
        "0x261D8c5e9742e6f7f1076Fa1F560894524e19cad",
        "0x50ff23E9A8D5DAc05744C367c9DDd588D027982B",
        "0x201B36B26b816D061fC552B679f8279Db0Fbbc6A",
      ],
      verified: false,
    },
    CultFactory: {
      address: "0x817e5E8409130C2bFd1C23c00a0F36d13fFe9093",
      abi: CultFactoryAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
