/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import AirdropContractAbi from "../../hardhat/constants/abis/AirdropContract.json";
import BondingCurveAbi from "../../hardhat/constants/abis/BondingCurve.json";
import CultAbi from "../../hardhat/constants/abis/Cult.json";
import CultFactoryAbi from "../../hardhat/constants/abis/CultFactory.json";
import CultRewardsAbi from "../../hardhat/constants/abis/CultRewards.json";
import { Abi } from "viem";
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  10143: {
    CultRewards: {
      address: "0x6ce743F0Cd70a0d7ad7fBE8d41Ff8Af70B72517b",
      abi: CultRewardsAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    BondingCurve: {
      address: "0xA118A791e4388522fba820E8e1b2DC70c2e39F81",
      abi: BondingCurveAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    AirdropContract: {
      address: "0x8E588eFd27AC02979437618Cfa67727C3574Ad04",
      abi: AirdropContractAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
    Cult: {
      address: "0x56eE3a5C45f4D7a1f50a427cb6B0F1005B2bD9B4",
      abi: CultAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [
        "0x71AF57DFDE2420426440B5cbCD5aB6695195925B",
        "0x6ce743F0Cd70a0d7ad7fBE8d41Ff8Af70B72517b",
        "0x261D8c5e9742e6f7f1076Fa1F560894524e19cad",
        "0x3dcc735c74f10fe2b9db2bb55c40fbbbf24490f7",
        "0x4c4eabd5fb1d1a7234a48692551eaecff8194ca7",
      ],
      verified: false,
    },

    CultFactory: {
      address: "0x98Bd8F988CEaC045395e45B8F7CEF5E2e49e7dB7",
      abi: CultFactoryAbi as Abi,
      inheritedFunctions: {},
      deploymentFile: "",
      deploymentScript: "deploy.js",
      constructorArgs: [],
      verified: false,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
