# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: cult
networks:
  - id: 10143
    start_block: 0
    contracts:
      - name: CultFactory
        abi_file_path: abis/CultFactory.json
        address:
          - 0xCE0da95A45bFa6a5A3f7e777D20D218f7ae5624D
        handler: src/EventHandlers.ts
        events:
          - event: CultTokenCreated(address indexed factoryAddress, address indexed tokenCreator, address protocolFeeRecipient, address bondingCurve, string tokenURI, string name, string symbol, address tokenAddress, address poolAddress, address airdropContract)
      - name: Cult
        abi_file_path: abis/Cult.json
        handler: src/EventHandlers.ts
        events:
          - event: CultTokenBuy(address indexed buyer, address indexed recipient, address indexed orderReferrer, uint256 totalEth, uint256 ethFee, uint256 ethSold, uint256 tokensBought, uint256 buyerTokenBalance, string comment, uint256 totalSupply, uint8 marketType)
          - event: CultTokenSell(address indexed seller, address indexed recipient, address indexed orderReferrer, uint256 totalEth, uint256 ethFee, uint256 ethBought, uint256 tokensSold, uint256 sellerTokenBalance, string comment, uint256 totalSupply, uint8 marketType)
          - event: CultTokenTransfer(address indexed from, address indexed to, uint256 amount, uint256 fromTokenBalance, uint256 toTokenBalance, uint256 totalSupply)
