# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: cult
networks:
  - id: 10143
    start_block: 7415670
    contracts:
      - name: CultFactory
        abi_file_path: abis/CultFactory.json
        address:
          - 0x49f7D95422982945ae3D990FC06d02bCD1E892bb
        handler: src/EventHandlers.ts
        events:
          - event: CultTokenCreated(address indexed factoryAddress, address indexed tokenCreator, address protocolFeeRecipient, address bondingCurve, string tokenURI, string name, string symbol, address tokenAddress, address poolAddress, address airdropContract)
      - name: Cult
        abi_file_path: abis/Cult.json
        handler: src/EventHandlers.ts
        events:
          - event: CultTokenBuy(address indexed buyer, address indexed recipient, address indexed orderReferrer, uint256 totalEth, uint256 ethFee, uint256 ethSold, uint256 tokensBought, uint256 buyerTokenBalance, string comment, uint256 totalSupply, uint8 marketType)
          - event: CultTokenSell(address indexed seller, address indexed recipient, address indexed orderReferrer, uint256 totalEth, uint256 ethFee, uint256 ethBought, uint256 tokensSold, uint256 sellerTokenBalance, string comment, uint256 totalSupply, uint8 marketType)
          - event: CultTokenTransfer(address indexed from, address indexed to, uint256 amount, uint256 fromTokenBalance, uint256 toTokenBalance, uint256 totalSupply)
          - event: CultTokenFees(address indexed tokenCreator, address indexed orderReferrer, address protocolFeeRecipient, uint256 tokenCreatorFee, uint256 orderReferrerFee, uint256 protocolFee)